### ISSUE TITLE
Change Csv.Row.{get,find}

### ISSUE THREAD

**Issue by rgrinberg** [Chris00/ocaml-csv#12]
Currently `Csv.Row.{get,find}` return `""` when the header/column index isn't present. I'm not sure why this is desirable but it seems like it would be much better if they returned a `string option` instead.

How do I tell the difference between an empty field and an absent field for example?

**Comment by Chris00** [comment]
On Tue, 1 Dec 2015 21:14:01 -0800, Rudi Grinberg wrote:
> 
> Currently Csv.Row.{get,find} return "" when the header/column index isn't present. I'm not sure why this is desirable but it seems like it would be much better if they returned a string option instead.
> 
> How do I tell the difference between an empty field and an absent field for example?

You do not because CSV does not do the distinction between the two.  In

a,,c

the second column is treated as empty — or missing but there is no way to distinguish the two.  Why should it be different if the column is in the last position?  Some programs — e.g. libreoffice — will automatically complete lines of a files by adding comas so that they all have the same length — thus treating missing columns as empty ones.

**Comment by rgrinberg** [comment]
I see, I was thinking of cases like like:

```
col1,col2,col3,col4
x,y,z
```

Where the 4th column is clearly missing. I agree it would just be confusing though.
